# Generated by Django 6.0.6 on 2026-07-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_director_product_rating_product_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isInStock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
