# Generated by Django 6.0.6 on 2026-07-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_isinstock_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='director',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
